# Generated by Django 5.1.3 on 2024-11-16 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='tittle',
            new_name='title',
        ),
    ]
